### ISSUE TITLE
Restriction on the order of input_files for ondemand simulator

### ISSUE THREAD

**Issue by piriwata** [maasblender/maasblender#98]
## Description:
When configuring the settings file for the ondemand simulator to include `matrix.json`, it is necessary to define the `input_files section` as follows:

```yaml
- name: ondemand
  input_files:
    - filename: gtfs_flee.zip
    - filename: matrix.json
```

The first entry in `input_files` must be the GTFS-FLEX file, and the second must be `matrix.json`.

## Proposed Solution:
- Dynamically detect file types/extensions, or
- Allow the configuration to specify files in any order.
